---
Resources:
  DMSEndpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      EngineName: aurora
      EndpointType: source
      Password: b@dP@$sW0rD
      Port: 3306
      ServerName: foobar
      Username: admin
