---
Parameters:
  DMSEndpointPassword:
    Type: String
    NoEcho: True
Resources:
  DMSEndpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      EngineName: aurora
      EndpointType: source
      Password: !Ref DMSEndpointPassword
      Port: 3306
      ServerName: foobar
      Username: admin
