---
Resources:
  DMSEndpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      EngineName: aurora
      EndpointType: source
      Password: '{{resolve:secretsmanager:/dms/endpoint/password:SecretString:password}}'
      Port: 3306
      ServerName: foobar
      Username: admin
