---
Parameters:
  DMSEndpointPassword:
    Type: String
    NoEcho: True
Resources:
  DMSEndpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      EngineName: aurora
      EndpointType: source
      Password: !Ref DMSEndpointPassword
      Port: 3306
      ServerName: foobar
      Username: admin
      MongoDbSettings:
        AuthMechanism: scram_sha_1
        AuthType: password
        Password: '{{resolve:ssm:UnsecureSecretString:1}}'
        Port: 27017
        ServerName: foobar
        Username: admin
