---
Resources:
  DMSEndpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      EngineName: aurora
      EndpointType: source
      Password: '{{resolve:ssm-secure:SecureSecretString:1}}'
      Port: 3306
      ServerName: foobar
      Username: admin
