---
Parameters:
  IamUserLoginPassword:
    Type: String
    NoEcho: True
Resources:
  MyIamUser:
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: !Ref IamUserLoginPassword
        PasswordResetRequired: true
        