---
Parameters:
  OpsWorksStackRdsDbInstancesDbPassword:
    Type: String
Resources:
  OpsWorksStack:
    Type: AWS::OpsWorks::Stack
    Properties:
      DefaultInstanceProfileArn: arn:aws:iam::123456789012:instance-profile/MyProfile-foobar
      Name: foobar
      ServiceRoleArn: arn:aws:iam::123456789012:role/MyRole-foobar
      RdsDbInstances: 
        - DbPassword: !Ref OpsWorksStackRdsDbInstancesDbPassword
          DbUser: admin
          RdsDbInstanceArn: arn:aws:rds:us-east-2:123456789012:db:foobar
