---
Resources:
  KinesisStream1:
    Type: AWS::Kinesis::Stream
    Properties: 
      Name: kinesisstream1
      ShardCount: 1
      StreamEncryption: 
        EncryptionType: KMS
        KeyId: arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012
  KinesisStream2:
    Type: AWS::Kinesis::Stream
    Properties: 
      Name: kinesisstream2
      ShardCount: 1
      StreamEncryption: 
        KeyId: arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012
  KinesisStream3:
    Type: AWS::Kinesis::Stream
    Properties: 
      Name: kinesisstream3
      ShardCount: 1
      StreamEncryption: 
        EncryptionType:
        KeyId: arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012