---
Resources:
  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: foo
      BranchName: bar
      BasicAuthConfig:
        Password: '{{resolve:ssm:UnsecureSecretString:1}}'
        Username: admin
