---
Resources:
  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: foo
      BranchName: bar
      BasicAuthConfig:
        Password: '{{resolve:secretsmanager:/amplify/branch/basicauthconfig_password:SecretString:password}}'
        Username: admin
