---
Parameters:
  AmplifyBranchBasicAuthConfigPassword:
    Type: String
Resources:
  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: foo
      BranchName: bar
      BasicAuthConfig:
        Password: !Ref AmplifyBranchBasicAuthConfigPassword
        Username: admin
