---
Parameters:
  AlexaASKSkillAuthenticationConfigurationRefreshToken:
    Type: String
    NoEcho: True
Resources:
  AlexaASKSkill:
    Type: Alexa::ASK::Skill
    Properties:
      SkillPackage:
        S3Bucket: foo-bucket
        S3Key: bar.zip
      AuthenticationConfiguration:
        ClientId: amzn1.application-oa2-client.foobar
        ClientSecret: '{{resolve:ssm-secure:SecureSecretString:1}}'
        RefreshToken: !Ref AlexaASKSkillAuthenticationConfigurationRefreshToken
      VendorId: foobar
