---
Parameters:
  AmplifyAppBasicAuthConfigPassword:
    Type: String
    NoEcho: True
    Default: b@dP@$sW0rD
Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      BasicAuthConfig:
        EnableBasicAuth: True
        Password: !Ref AmplifyAppBasicAuthConfigPassword
        Username: admin
      Name: foobar
