---
Parameters:
  AmplifyAppOauthToken:
    Type: String
    NoEcho: True
    Default: b@d0@u7H70K3n
Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      OauthToken: !Ref AmplifyAppOauthToken
      Name: foobar
