---
Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      BasicAuthConfig:
        EnableBasicAuth: True
        Password: '{{resolve:secretsmanager:/amplify/app/basicauthconfig_password:SecretString:password}}'
        Username: admin
      Name: foobar
