---
Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      BasicAuthConfig:
        EnableBasicAuth: True
        Password: '{{resolve:ssm-secure:SecureSecretString:1}}'
        Username: admin
      Name: foobar
