---
Parameters:
  AmplifyAppBasicAuthConfigPassword:
    Type: String
Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      BasicAuthConfig:
        EnableBasicAuth: True
        Password: !Ref AmplifyAppBasicAuthConfigPassword
        Username: admin
      Name: foobar
