---
Resources:
  MicrosoftAD:
    Type: AWS::DirectoryService::MicrosoftAD
    Properties:
      Name: microsoftad.foobar.com
      Password: '{{resolve:secretsmanager:/directory_service/microsoft_ad/password:SecretString:password}}'
      VpcSettings:
        SubnetIds:
          - subnet-foobar
          - subnet-foobaz
        VpcId: vpc-foobar
