---
Parameters:
  MicrosoftADPassword:
    Type: String
    NoEcho: True
    Default: b@dP@$sW0rD
Resources:
  MicrosoftAD:
    Type: AWS::DirectoryService::MicrosoftAD
    Properties:
      Name: microsoftad.foobar.com
      Password: !Ref MicrosoftADPassword
      VpcSettings:
        SubnetIds:
          - subnet-foobar
          - subnet-foobaz
        VpcId: vpc-foobar
