---
Resources:
  MicrosoftAD:
    Type: AWS::DirectoryService::MicrosoftAD
    Properties:
      Name: microsoftad.foobar.com
      Password: '{{resolve:ssm:UnsecureSecretString:1}}'
      VpcSettings:
        SubnetIds:
          - subnet-foobar
          - subnet-foobaz
        VpcId: vpc-foobar
