AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Enable:
    Type: String
Conditions:
  EnableLogsPublicLB: !Ref Enable
Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: !If
      - EnableLogsPublicLB

      - LoadBalancerAttributes:
          - Key: access_logs.s3.enabled
            Value: 'true'
          - Key: access_logs.s3.bucket
            Value:
              Fn::ImportValue: !Sub '${Project}-${ApplicationGroup}-${Environment}-${BucketLogsNameSuffix}'
          - Key: access_logs.s3.prefix
            Value: loadbalancer
      - LoadBalancerAttributes:
          - Key: access_logs.s3.enabled
            Value: 'false'