---
Resources:
  ManagedPolicyFail1:
    Type: AWS::IAM::ManagedPolicy 
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Action: "iam:PassRole"
            Resource: "*"

  ManagedPolicyFail2:
    Type: AWS::IAM::ManagedPolicy 
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Action: "iam:Pas*"
            Resource: "*"

  ManagedPolicyFail3:
    Type: AWS::IAM::ManagedPolicy 
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Action: "iam:*Role"
            Resource: "*"

  ManagedPolicyFail4:
    Type: AWS::IAM::ManagedPolicy 
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Action: "iam:*Ro*"
            Resource: "*"

  ManagedPolicyFail5:
    Type: AWS::IAM::ManagedPolicy 
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Action: "*"
            Resource: "*"
