---
Parameters:
  DBClusterMasterUserPassword:
    Type: String
    NoEcho: True
Conditions:
  Foobar: foobar
Resources:
  RDSDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DeletionProtection: True
      Engine: aurora-mysql
      MasterUserPassword: !If [ Foobar, !Ref 'AWS::NoValue', !Ref DBClusterMasterUserPassword ]
      MasterUsername: !If [ Foobar, !Ref 'AWS::NoValue', admin ]
      Port: 3306
