---
Resources:
  AppStreamDirectoryConfig:
    Type: AWS::AppStream::DirectoryConfig
    Properties:
      OrganizationalUnitDistinguishedNames:
        - foo
        - bar
        - baz
      ServiceAccountCredentials:
        AccountName: admin
        AccountPassword: b@dP@$sW0rD
      DirectoryName: foobar.example.com
