---
Parameters:
  AppStreamDirectoryConfigServiceAccountCredentialsAccountPassword:
    Type: String
Resources:
  AppStreamDirectoryConfig:
    Type: AWS::AppStream::DirectoryConfig
    Properties:
      OrganizationalUnitDistinguishedNames:
        - foo
        - bar
        - baz
      ServiceAccountCredentials:
        AccountName: admin
        AccountPassword: !Ref AppStreamDirectoryConfigServiceAccountCredentialsAccountPassword
      DirectoryName: foobar.example.com
