---
Resources:
  AppStreamDirectoryConfig:
    Type: AWS::AppStream::DirectoryConfig
    Properties:
      OrganizationalUnitDistinguishedNames:
        - foo
        - bar
        - baz
      ServiceAccountCredentials:
        AccountName: admin
      DirectoryName: foobar.example.com
