Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: jimbob
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: !Join [ "", [ "Delete Previous > ", !Ref PreviousLifeCycle, " Days" ] ]
            NoncurrentVersionExpirationInDays: !Ref PreviousLifeCycle
            Status: Enabled

  Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: jimbob2
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: !Join [ "", [ "Delete Previous > ", !Ref PreviousLifeCycle, " Days" ] ]
            NoncurrentVersionExpirationInDays: !Ref PreviousLifeCycle
            Status: Enabled

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2008-10-17'
        Statement:
          -
            Sid: "Deny Unencrypted Put Object"
            Effect: Deny
            Principal: "*"
            Action:
              - "s3:PutObject"
            Resource: !Join [ "", [ "arn:aws:s3:::", !Ref Bucket, "/*" ] ]
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption:
                  - "AES256"
                  - "aws:kms"
