---
Parameters:
  KmsMasterKeyId:
    Type: String
    Default: arn:aws:kms:us-east-1:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab

Resources:
  SqsQueue1:
    Type: AWS::SQS::Queue
    Properties: 
      KmsMasterKeyId: !Ref KmsMasterKeyId
      QueueName: sqsqueue1

  SqsQueue2:
    Type: AWS::SQS::Queue
    Properties: 
      KmsMasterKeyId: !Ref KmsMasterKeyId
      QueueName: sqsqueue2